import { useEffect, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Alert, Button, Card, Col, Descriptions, Divider, Form, Input, InputNumber, Modal, Popconfirm, Progress, Row, Select, Space, Statistic, Table, Tabs, Tag, Typography, message } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import dayjs from 'dayjs'
import { api } from '@/lib/api'

const { Title, Text } = Typography
type Food = { provider_food_id: string; description: string; data_type?: string; id?: number; calories_per_100g?: number; protein_g_per_100g?: number; carbohydrate_g_per_100g?: number; fat_g_per_100g?: number; fiber_g_per_100g?: number; allergen_status?: string }
type Item = { food_name: string; quantity: number; unit: string; grams?: number; calories: number; protein_g?: number; carbohydrate_g?: number; fat_g?: number; fiber_g?: number; source: 'usda' | 'manual_estimate'; food_cache_id?: number }
type Meal = { id: number; eaten_at: string; meal_type: string; notes?: string; items: Item[] }
type Summary = { calories: number; protein_g: number; carbohydrate_g: number; fat_g: number; fiber_g: number; meal_count: number; calorie_adherence_pct?: number; protein_adherence_pct?: number; remaining: Record<string, number | null>; target?: { calorie_target_kcal: number; protein_target_g: number; carbohydrate_target_g: number; fat_target_g: number; fiber_target_g: number } }
type Profile = { sex_for_energy_equation: string; activity_level: string; nutrition_goal: string; dietary_preferences: string[]; dietary_restrictions: string[]; allergies: string[] }

const date = () => dayjs().format('YYYY-MM-DD')
const nutritionKey = ['nutrition'] as const

function TodayTab() {
  const summary = useQuery({ queryKey: [...nutritionKey, 'summary', date()], queryFn: () => api.post<Summary>('/nutrition/daily-summary', { date: date() }) })
  if (summary.isError) return <Alert type="error" showIcon title={(summary.error as Error).message} />
  const data = summary.data
  const cards = [{ label: 'Calories', value: data?.calories, target: data?.target?.calorie_target_kcal, remaining: data?.remaining.calories }, { label: 'Protein (g)', value: data?.protein_g, target: data?.target?.protein_target_g, remaining: data?.remaining.protein_g }, { label: 'Carbs (g)', value: data?.carbohydrate_g, target: data?.target?.carbohydrate_target_g, remaining: data?.remaining.carbohydrate_g }, { label: 'Fat (g)', value: data?.fat_g, target: data?.target?.fat_target_g, remaining: data?.remaining.fat_g }]
  return <Space direction="vertical" size="large" style={{ width: '100%' }}>
    <Row gutter={[16, 16]}>{cards.map(card => <Col xs={24} sm={12} lg={6} key={card.label}><Card loading={summary.isLoading}><Statistic title={card.label} value={card.value || 0} suffix={card.target ? ` / ${card.target}` : ''} /><Text type="secondary">Remaining: {card.remaining ?? 'Set targets'}</Text></Card></Col>)}</Row>
    <Card title="Today’s adherence" loading={summary.isLoading}><Row gutter={24}><Col span={12}><Text>Calories</Text><Progress percent={Math.min(Number(data?.calorie_adherence_pct || 0), 100)} /></Col><Col span={12}><Text>Protein</Text><Progress percent={Math.min(Number(data?.protein_adherence_pct || 0), 100)} /></Col></Row><Divider /><Text type="secondary">{data?.meal_count || 0} meal(s) logged today. Values above 100% mean the target was exceeded.</Text></Card>
  </Space>
}
function MealLogTab() {
  type MealForm = { meal_type: string; food: string[]; grams: number; notes?: string; calories?: number; protein_g?: number; carbohydrate_g?: number; fat_g?: number; fiber_g?: number }
  const client = useQueryClient(); const [form] = Form.useForm<MealForm>(); const [open, setOpen] = useState(false); const [catalogueSession, setCatalogueSession] = useState(0); const [messageApi, holder] = message.useMessage()
  const meals = useQuery({ queryKey: [...nutritionKey, 'meals', date()], queryFn: () => api.post<{ items: Meal[] }>('/nutrition/meals/list', { date: date() }) })
  const catalogue = useQuery({ queryKey: [...nutritionKey, 'foods', 'catalogue', catalogueSession], queryFn: () => api.post<{ items: Food[] }>('/nutrition/foods/catalogue', { limit: 200 }), enabled: open, staleTime: Infinity })
  const selectedValue = Form.useWatch('food', form)?.[0]; const grams = Form.useWatch('grams', form) || 0; const selected = catalogue.data?.items.find(food => food.provider_food_id === selectedValue); const isManual = Boolean(selectedValue) && !selected
  const save = useMutation({ mutationFn: (values: MealForm) => { const grams = values.grams; if (!selectedValue) throw new Error('Select a catalogue food or enter a manual food name.'); const item: Item = selected ? { food_name: selected.description, quantity: grams, unit: 'g', grams, calories: Number(selected.calories_per_100g) * grams / 100, protein_g: Number(selected.protein_g_per_100g) * grams / 100, carbohydrate_g: Number(selected.carbohydrate_g_per_100g) * grams / 100, fat_g: Number(selected.fat_g_per_100g) * grams / 100, fiber_g: Number(selected.fiber_g_per_100g || 0) * grams / 100, source: 'usda', food_cache_id: selected.id } : { food_name: selectedValue, quantity: grams, unit: 'g', grams, calories: values.calories!, protein_g: values.protein_g!, carbohydrate_g: values.carbohydrate_g!, fat_g: values.fat_g!, fiber_g: values.fiber_g || 0, source: 'manual_estimate' }; return api.post('/nutrition/meals', { eaten_at: new Date().toISOString(), meal_type: values.meal_type, notes: values.notes, items: [item] }) }, onSuccess: async () => { messageApi.success('Meal logged'); setOpen(false); form.resetFields(); await client.invalidateQueries({ queryKey: nutritionKey }) }, onError: (error: Error) => messageApi.error(error.message) })
  const columns: ColumnsType<Meal> = [{ title: 'Time', dataIndex: 'eaten_at', render: value => dayjs(value).format('h:mm A') }, { title: 'Meal', dataIndex: 'meal_type' }, { title: 'Items', render: (_, meal) => meal.items.map(item => <div key={item.food_name}>{item.food_name} <Tag color={item.source === 'usda' ? 'green' : 'gold'}>{item.source === 'usda' ? 'USDA' : 'Estimated'}</Tag></div>) }]
  const nutrition = selected && [['Calories', Number(selected.calories_per_100g)], ['Protein (g)', Number(selected.protein_g_per_100g)], ['Carbohydrates (g)', Number(selected.carbohydrate_g_per_100g)], ['Fat (g)', Number(selected.fat_g_per_100g)]].map(([label, per100g]) => ({ key: String(label), label: String(label), children: `${per100g} per 100g · ${(per100g * grams / 100).toFixed(1)} per portion` }))
  return (
    <>
      <Space style={{ marginBottom: 16 }}><Button type="primary" onClick={() => { form.resetFields(); setCatalogueSession(session => session + 1); setOpen(true) }}>Log meal</Button><Button onClick={() => meals.refetch()}>Refresh</Button></Space>
      {holder}{meals.isError && <Alert type="error" showIcon title={(meals.error as Error).message} style={{ marginBottom: 16 }} />}
      <Table rowKey="id" loading={meals.isLoading} columns={columns} dataSource={meals.data?.items || []} locale={{ emptyText: 'No meals logged today.' }} pagination={false} />
      <Modal title="Confirm meal log" open={open} onCancel={() => setOpen(false)} onOk={() => form.submit()} okText="Confirm and log" confirmLoading={save.isPending} forceRender>
        <Alert type="info" showIcon title="Choose a USDA food or enter a manual food with explicit nutrient values." style={{ marginBottom: 16 }} />
        {catalogue.isError && <Alert type="warning" showIcon title="The local USDA catalogue could not be loaded. You can still enter a manual food." style={{ marginBottom: 16 }} />}
        <Form form={form} layout="vertical" initialValues={{ meal_type: 'lunch', grams: 100 }} onFinish={save.mutate}>
          <Form.Item name="meal_type" label="Meal" rules={[{ required: true }]}><Select options={['breakfast', 'lunch', 'dinner', 'snack'].map(value => ({ value }))} /></Form.Item>
          <Form.Item name="food" label="Food" rules={[{ required: true, message: 'Select a USDA food or type a manual food name' }]}><Select mode="tags" maxCount={1} showSearch loading={catalogue.isFetching} optionFilterProp="label" options={(catalogue.data?.items || []).map(food => ({ value: food.provider_food_id, label: food.description }))} placeholder="Search local USDA catalogue or type a manual food" /></Form.Item>
          <Form.Item name="grams" label="Portion (grams)" rules={[{ required: true }]}><InputNumber min={1} precision={0} style={{ width: '100%' }} /></Form.Item>
          {selected && <Descriptions size="small" title="Verified USDA nutrients" items={nutrition || []} />}
          {isManual && <>
            <Alert type="warning" showIcon title="Manual estimate: enter every macro explicitly. Zero is accepted when intentional." style={{ margin: '16px 0' }} />
            <Row gutter={16}>{(['calories', 'protein_g', 'carbohydrate_g', 'fat_g'] as const).map(name => <Col span={12} key={name}><Form.Item name={name} label={{ calories: 'Calories', protein_g: 'Protein (g)', carbohydrate_g: 'Carbohydrates (g)', fat_g: 'Fat (g)' }[name]} rules={[{ required: true, message: 'This value is required' }]}><InputNumber min={0} style={{ width: '100%' }} /></Form.Item></Col>)}<Col span={12}><Form.Item name="fiber_g" label="Fiber (g)"><InputNumber min={0} style={{ width: '100%' }} /></Form.Item></Col></Row>
          </>}
          <Form.Item name="notes" label="Notes"><Input /></Form.Item>
        </Form>
      </Modal>
    </>
  )
}

function ProfileTab() {
  const client = useQueryClient(); const [form] = Form.useForm(); const [messageApi, holder] = message.useMessage(); const profile = useQuery({ queryKey: [...nutritionKey, 'profile'], queryFn: () => api.post<Profile>('/nutrition/profile/get', {}) }); const targets = useQuery({ queryKey: [...nutritionKey, 'targets'], queryFn: () => api.post<Summary['target']>('/nutrition/targets/active', {}) }); const save = useMutation({ mutationFn: (values: Profile) => api.post('/nutrition/profile/save', values), onSuccess: async () => { messageApi.success('Profile saved. Review and apply new targets separately.'); await client.invalidateQueries({ queryKey: nutritionKey }) }, onError: (e: Error) => messageApi.error(e.message) }); const apply = useMutation({ mutationFn: () => api.post('/nutrition/targets/calculate', { confirm_apply: true }), onSuccess: () => { messageApi.success('Targets applied'); client.invalidateQueries({ queryKey: nutritionKey }) }, onError: (e: Error) => messageApi.error(e.message) }); useEffect(() => { if (profile.data) form.setFieldsValue(profile.data) }, [form, profile.data]); return <>{holder}{profile.isError && <Alert type="error" title={(profile.error as Error).message} />}{targets.data && <Card title="Active targets" style={{ marginBottom: 16 }}><Descriptions items={Object.entries(targets.data).filter(([, value]) => typeof value === 'number').map(([label, value]) => ({ key: label, label, children: value }))} /></Card>}<Card title="Profile & targets" loading={profile.isLoading}><Form form={form} layout="vertical" onFinish={save.mutate}><Row gutter={16}><Col span={8}><Form.Item name="sex_for_energy_equation" label="Sex for energy equation" rules={[{ required: true }]}><Select options={['female', 'male'].map(value => ({ value }))} /></Form.Item></Col><Col span={8}><Form.Item name="activity_level" label="Activity level" rules={[{ required: true }]}><Select options={['sedentary', 'light', 'moderate', 'very_active', 'extra_active'].map(value => ({ value }))} /></Form.Item></Col><Col span={8}><Form.Item name="nutrition_goal" label="Nutrition goal" rules={[{ required: true }]}><Select options={['maintenance', 'fat_loss', 'muscle_gain', 'performance'].map(value => ({ value }))} /></Form.Item></Col></Row>{(['dietary_preferences', 'dietary_restrictions', 'allergies'] as const).map(name => <Form.Item key={name} name={name} label={name.replaceAll('_', ' ')}><Select mode="tags" /></Form.Item>)}<Space><Button type="primary" htmlType="submit" loading={save.isPending}>Save profile</Button><Popconfirm title="Apply updated targets now?" description="This records a new target snapshot." onConfirm={() => apply.mutate()}><Button loading={apply.isPending}>Confirm and apply targets</Button></Popconfirm></Space></Form></Card></>
}

function ProgressTab() { const end = date(); const start = dayjs().subtract(6, 'day').format('YYYY-MM-DD'); const query = useQuery({ queryKey: [...nutritionKey, 'adherence', start, end], queryFn: () => api.post<{ items: (Summary & { summary_date: string })[] }>('/nutrition/adherence', { from_date: start, to_date: end }) }); return <Card title="Last 7 days" loading={query.isLoading}>{query.isError ? <Alert type="error" title={(query.error as Error).message} /> : <Table rowKey="summary_date" pagination={false} dataSource={query.data?.items || []} columns={[{ title: 'Date', dataIndex: 'summary_date' }, { title: 'Calories', dataIndex: 'calories' }, { title: 'Protein (g)', dataIndex: 'protein_g' }, { title: 'Calorie adherence', dataIndex: 'calorie_adherence_pct', render: value => value == null ? 'No target' : `${value}%` }]} />}</Card> }

export function NutritionPage() { return <div><Title level={2}>Nutrition</Title><Text type="secondary">Track user-owned meals, USDA-backed food data, targets, and adherence.</Text><Card style={{ marginTop: 24 }}><Tabs items={[{ key: 'today', label: 'Today', children: <TodayTab /> }, { key: 'meals', label: 'Meal Log', children: <MealLogTab /> }, { key: 'profile', label: 'Profile & Targets', children: <ProfileTab /> }, { key: 'progress', label: 'Progress', children: <ProgressTab /> }]} /></Card></div> }